### PR TITLE
Card control

### PR DESCRIPTION
**Pull request by plfiorini**
Add a Card control with a Material style.
Of course the Material design will be used only when the Material
style is used.

### CODE REVIEW

**Comment by plfiorini** [comment]
Here's how it looks like with the Material style:

screenshot from 2016-07-26 08-12-16

**Comment by plfiorini** [comment]
Don't mind the Explose button, that was already renamed into Explore

**Comment by plfiorini** [comment]
@iBeliever Any objection on this, can I merge?

**Comment by iBeliever** [comment]
Looks nice! I wonder if we could have a couple of subclasses for common card layouts featured on the Google Material Design spec page?

**Comment by plfiorini** [comment]
We can try with a more specialized version with common properties but seems hard.
The following cards:

https://material-design.storage.googleapis.com/publish/material_v_8/material_ext_publish/0Bzhp5Z4wHba3cXVadmtJa19wT3M/components_cards_content1.png
https://material-design.storage.googleapis.com/publish/material_v_8/material_ext_publish/0Bzhp5Z4wHba3NGo3QkpVWTNBZzA/components_cards_content3.png

have in common the following:

* actionBar: you can put either a Row with ActionButtons or a Row with Buttons
* contentItem: Discover example has an image while Feed Reader example has a layout with text and images

This:

https://material-design.storage.googleapis.com/publish/material_v_8/material_ext_publish/0Bzhp5Z4wHba3MHh2ZlhHVUMyQlk/components_cards17.png

shows a basic structure with an icon, title, subtitle, rich media, supporting text and actions.

Then this one has a completely different layout:

https://material-design.storage.googleapis.com/publish/material_v_8/material_ext_publish/0Bzhp5Z4wHba3aHp5aGtIT0dwQ28/components_cards19.png

**Comment by plfiorini** [comment]
@iBeliever For now if you agree I would merge the base version

**Comment by iBeliever** [comment]
Merged!

**Pull request merged**
